Repository movieget/backend, pull requests merged in 2024-10, with the labels that each got.

#2 Develop
  .gitignore
  app/core/__init__.py
  app/main.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement, help wanted

#3 Update issue templates
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
Labels: good first issue

#4 Update issue templates
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
Labels: documentation

#5 Create pull_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: documentation

#6 Init: Project init
  .github/workflows/CI.yml
  .gitignore
  .gitmessage.txt
  README.md
  app/User/dto/__init__.py
  app/User/entity/__init__.py
  app/User/entity/user.py
  app/common/__init__.py
  app/controller/user.py
  app/core/config.py
  app/core/security.py
  app/database/__init__.py
  app/database/connection.py
  app/main.py
  app/repository/__init__.py
  app/schemas/__init__.py
  app/service/__init__.py
  poetry.lock
  pyproject.toml
Labels: documentation

#7 frist_commit
  app/User/test.py
Labels: documentation

#8 Revert "frist_commit"
  app/User/test.py
Labels: documentation

#12 Project/init
  .gitignore
  README.md
  app/User/dto/__init__.py
  app/User/entity/__init__.py
  app/User/entity/user.py
  app/common/__init__.py
  app/controller/user.py
  app/core/__init__.py
  app/core/config.py
  app/core/security.py
  app/database/__init__.py
  app/database/connection.py
  app/main.py
  app/repository/__init__.py
  app/schemas/__init__.py
  app/service/__init__.py
Labels: enhancement

#13 Chore: Change Project Folder
  scripts/test.sh
  src/common/base_models/__init__.py
Labels: documentation, enhancement

#14 Feat: Total DB Schema
  poetry.lock
  pyproject.toml
  src/app/api/__init__.py
  src/app/api/root_routes.py
  src/app/api/v1_routes/__init__.py
  src/app/api/v1_routes/user.py
  src/app/controller/user.py
  src/app/v1/user/entity/alert.py
  src/app/v1/user/entity/cinema.py
  src/app/v1/user/entity/favorite.py
  src/app/v1/user/entity/location.py
  src/app/v1/user/entity/movie.py
  src/app/v1/user/entity/payment.py
  src/app/v1/user/entity/payment_history.py
  src/app/v1/user/entity/refund.py
  src/app/v1/user/entity/review.py
  src/app/v1/user/entity/screen.py
  src/app/v1/user/entity/screen_info.py
  src/app/v1/user/entity/seats.py
  src/app/v1/user/schemas/user.py
  src/common/handlers/router_handler.py
  src/common/models/__init__.py
  src/common/models/base_model.py
  src/common/models/consts.py
  src/common/post_construct.py
  src/core/configs/database_config.py
  src/main.py
Labels: enhancement

#15 feat:entity-3files upgrade
  src/app/v1/user/entity/alert.py
  src/app/v1/user/entity/book.py
  src/app/v1/user/entity/favorite.py
  src/app/v1/user/entity/review.py
  src/common/models/base_models/BaseModel.py
  src/common/models/base_models/__init__.py
  src/common/models/base_models/constant.py
Labels: documentation

#16 Feature
  src/app/v1/user/entity/payment.py
  src/app/v1/user/entity/payment_history.py
  src/app/v1/user/entity/refund.py
  src/common/models/consts.py
Labels: enhancement

#17 Fix: DB Schema Update
  src/app/v1/user/entity/cinema.py
  src/app/v1/user/entity/favorite.py
  src/app/v1/user/entity/location.py
  src/app/v1/user/entity/movie.py
  src/app/v1/user/entity/refund.py
  src/app/v1/user/entity/screen.py
  src/app/v1/user/entity/screen_info.py
  src/app/v1/user/entity/seat.py
  src/common/models/base_models/BaseModel.py
  src/common/models/base_models/__init__.py
  src/common/models/base_models/constant.py
  src/common/models/consts.py
Labels: enhancement

#19 Fix: Change APP Structure
  pyproject.toml
  src/app/v1/alert/entity/__init__.py
  src/app/v1/alert/entity/alert.py
  src/app/v1/alert/repository/__init__.py
  src/app/v1/alert/schemas/__init__.py
  src/app/v1/alert/service/__init__.py
  src/app/v1/book/entity/__init__.py
  src/app/v1/book/entity/book.py
  src/app/v1/book/repository/__init__.py
  src/app/v1/book/schemas/__init__.py
  src/app/v1/book/service/__init__.py
  src/app/v1/cinema/entity/__init__.py
  src/app/v1/cinema/entity/cinema.py
  src/app/v1/cinema/repository/__init__.py
  src/app/v1/cinema/schemas/__init__.py
  src/app/v1/cinema/service/__init__.py
  src/app/v1/favorite/entity/__init__.py
  src/app/v1/favorite/entity/favorite.py
  src/app/v1/favorite/repository/__init__.py
  src/app/v1/favorite/schemas/__init__.py
  src/app/v1/favorite/service/__init__.py
  src/app/v1/location/entity/__init__.py
  src/app/v1/location/entity/location.py
  src/app/v1/location/repository/__init__.py
  src/app/v1/location/schemas/__init__.py
  src/app/v1/location/service/__init__.py
  src/app/v1/movie/entity/__init__.py
  src/app/v1/movie/entity/movie.py
  src/app/v1/movie/repository/__init__.py
  src/app/v1/movie/schemas/__init__.py
  src/app/v1/movie/service/__init__.py
  src/app/v1/payment/entity/__init__.py
  src/app/v1/payment/entity/payment.py
  src/app/v1/payment/entity/payment_history.py
  src/app/v1/payment/repository/__init__.py
  src/app/v1/payment/schemas/__init__.py
  src/app/v1/payment/service/__init__.py
  src/app/v1/refund/entity/__init__.py
  src/app/v1/refund/entity/refund.py
  src/app/v1/refund/repository/__init__.py
  src/app/v1/refund/schemas/__init__.py
  src/app/v1/refund/service/__init__.py
  src/app/v1/review/entity/__init__.py
  src/app/v1/review/entity/review.py
  src/app/v1/review/repository/__init__.py
  src/app/v1/review/schemas/__init__.py
  src/app/v1/review/service/__init__.py
  src/app/v1/screen/entity/__init__.py
  src/app/v1/screen/entity/screen.py
  src/app/v1/screen/entity/screen_info.py
  src/app/v1/screen/entity/seat.py
  src/app/v1/screen/repository/__init__.py
  src/app/v1/screen/schemas/__init__.py
  src/app/v1/screen/service/__init__.py
  src/app/v1/user/entity/alert.py
Labels: enhancement

#20 Feat: Add Schemas
  .gitignore
  README.md
  src/app/v1/alert/entity/alert.py
  src/app/v1/book/entity/book.py
  src/app/v1/cinema/entity/cinema.py
  src/app/v1/favorite/entity/favorite.py
  src/app/v1/location/entity/location.py
  src/app/v1/movie/entity/movie.py
  src/app/v1/payment/entity/payment.py
  src/app/v1/payment/entity/payment_history.py
  src/app/v1/refund/entity/refund.py
  src/app/v1/review/entity/review.py
  src/app/v1/screen/entity/screen.py
  src/app/v1/screen/entity/screen_info.py
  src/app/v1/screen/entity/seat.py
  src/app/v1/user/entity/user.py
  src/common/models/consts.py
  src/common/post_construct.py
  src/core/configs/database_config.py
  src/core/database/connection.py
  src/main.py
Labels: documentation

#21 Feat: Add Terraform EC2
  .gitignore
  Terraform/EC2/main.tf
Labels: enhancement

#23 Feat: Change DB Schema
  .gitignore
  src/app/v1/alert/entity/alert.py
  src/app/v1/book/entity/book.py
  src/app/v1/cinema/entity/cinema.py
  src/app/v1/favorite/entity/favorite.py
  src/app/v1/payment/entity/payment.py
  src/app/v1/review/entity/review.py
  src/app/v1/screen/entity/screen.py
  src/app/v1/screen/entity/screen_info.py
  src/app/v1/screen/entity/seat.py
  src/app/v1/user/entity/user.py
  src/core/configs/database_config.py
Labels: enhancement

#25 Feat: kakao login(signup)
  .gitignore
  src/app/api/root_routes.py
  src/app/api/v1_routes/user.py
  src/app/v1/user/schemas/user.py
  src/app/v1/user/service/oauth_service.py
  src/common/models/base_model.py
  src/core/configs/database_config.py
  src/core/database/connection.py
  src/core/security.py
  src/main.py
Labels: enhancement

#27 Add bookseat.py, screen_info.py, consts.py, cinama.py
  src/app/v1/book/entity/bookseat.py
  src/app/v1/book/schemas/book.py
  src/app/v1/cinema/entity/cinema.py
  src/app/v1/screen/entity/screen_info.py
  src/common/models/consts.py
Labels: good first issue

#28 Fix: Separate actor image field from movie table
  src/app/v1/movie/entity/actor_image.py
  src/app/v1/movie/entity/movie.py
Labels: enhancement, good first issue

#30 <FEAT>:<new_model추가>기존모델 일부수정actor_image,book_seat추가
  src/app/v1/alert/entity/alert.py
  src/app/v1/book/entity/book.py
  src/app/v1/cinema/entity/cinema.py
  src/app/v1/favorite/entity/favorite.py
  src/app/v1/movie/entity/actor_image.py
  src/app/v1/movie/entity/movie.py
  src/app/v1/payment/entity/payment.py
  src/app/v1/payment/entity/payment_history.py
  src/app/v1/refund/entity/refund.py
  src/app/v1/review/entity/review.py
  src/app/v1/screen/entity/screen.py
  src/common/models/consts.py
  src/core/configs/database_config.py
Labels: good first issue

#31 Refactor: Terraform Code
  .gitignore
  Terraform/main.tf
Labels: enhancement

#32 Refactor: Terraform Code
  Terraform/main.tf
Labels: enhancement

#33 Feat: Add Nginx
  infra/README.md
  infra/nginx/compose.yml
  infra/nginx/index.html
  infra/nginx/nginx.conf
Labels: enhancement

#34 feat: Add Gunicorn, CI/CD yml, Dockerfile
  .dockerignore
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile
  poetry.lock
  pyproject.toml
  src/app/api/v1_routes/user.py
  src/app/v1/alert/entity/alert.py
  src/app/v1/cinema/entity/cinema.py
  src/app/v1/favorite/entity/favorite.py
  src/app/v1/movie/entity/actor_image.py
  src/app/v1/movie/entity/movie.py
  src/app/v1/refund/entity/refund.py
  src/app/v1/screen/entity/screen.py
  src/core/configs/__init__.py
  src/core/security.py
  src/main.py
Labels: enhancement

#35 feat: Add Gunicorn, CI/CD yml, Dockerfile, pytest-cov
  .github/workflows/CD.yml
Labels: enhancement

#41 feat: Add absolute path in main.py & aiohttp library
  .github/workflows/CI.yml
  poetry.lock
  pyproject.toml
  src/main.py
Labels: enhancement

#47 Fix: nginx.conf, CD.yml
  .github/workflows/CD.yml
  infra/nginx/nginx.conf
Labels: enhancement

#48 feat: booking system
  scripts/init_seats.py
  src/app/api/root_routes.py
  src/app/api/v1_routes/book_option_router.py
  src/app/api/v1_routes/cancel_router.py
  src/app/api/v1_routes/confirm_router.py
  src/app/api/v1_routes/payment_result_router.py
  src/app/api/v1_routes/payment_router.py
  src/app/api/v1_routes/seats_router.py
  src/app/v1/book/repository/book_repository.py
  src/app/v1/book/schemas/book.py
  src/app/v1/book/service/book_service.py
  src/app/v1/book/service/movie_service.py
  src/app/v1/book/service/seat_service.py
  src/app/v1/payment/service/payment_service.py
  src/app/v1/screen/entity/seat.py
  src/app/v1/user/dependencies.py
  src/core/configs/seat_layouts.py
  src/core/database/connection.py
  src/main.py
Labels: documentation

#49 feat: created seats
  src/app/v1/screen/service/seat_service.py
  src/core/configs/seat_layouts.py
Labels: documentation

#50 feat: remove Depends
  src/app/api/root_routes.py
  src/app/api/v1_routes/book_option_router.py
  src/app/api/v1_routes/cancel_router.py
  src/app/api/v1_routes/confirm_router.py
  src/app/api/v1_routes/payment_result_router.py
  src/app/api/v1_routes/payment_router.py
  src/app/api/v1_routes/seats_router.py
  src/app/v1/book/schemas/book.py
  src/app/v1/user/dependencies.py
  src/main.py
Labels: documentation

#51 feat:modified books
  src/app/api/root.py
  src/app/api/v1_routes/book.py
  src/app/api/v1_routes/book_option_router.py
  src/app/api/v1_routes/cancel_router.py
  src/app/api/v1_routes/confirm_router.py
  src/app/api/v1_routes/payment_result_router.py
  src/app/api/v1_routes/seats_router.py
  src/app/v1/book/repository/book_repository.py
  src/app/v1/book/schemas/book.py
  src/app/v1/book/schemas/request.py
  src/app/v1/book/schemas/response.py
  src/main.py
Labels: documentation

#52 feat: check content
  .github/pull_request_template.md
  src/app/api/root.py
  src/app/api/v1_routes/favorite.py
  src/app/v1/favorite/repository/favorite_repository.py
  src/app/v1/favorite/schemas/requestDto.py
  src/app/v1/favorite/schemas/responseDto.py
  src/app/v1/favorite/service/favorite_service.py
  src/app/v1/movie/repository/movie_repository.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schemas/user.py
  src/common/handlers/db_handler.py
  src/common/handlers/exception_handler.py
  src/common/models/base_model.py
  src/common/models/consts.py
  src/core/database/connection.py
  src/core/factory.py
  src/main.py
Labels: enhancement

#53 Login/kakao
  src/app/api/v1_routes/user.py
  src/app/api/v1_routes/user_kakao.py
  src/app/v1/user/service/oauth_service.py
  src/app/v1/user/service/redis.py
  src/common/utils/redis.py
  src/core/configs/database_config.py
  src/core/security.py
Labels: enhancement

#55 feat: add CORS, Redis, Root API fixed
  poetry.lock
  pyproject.toml
  src/main.py
Labels: documentation, enhancement

#70 feat: unlimit CORS
  src/app/api/v1_routes/user_kakao.py
  src/app/v1/payment/entity/payment.py
  src/main.py
Labels: enhancement

#72 feat: unlimit CORS
  src/app/api/v1_routes/user_kakao.py
Labels: enhancement

#119 Feature/books
  scripts/init_seats.py
  src/app/api/v1_routes/book.py
  src/app/api/v1_routes/user.py
  src/app/v1/screen/service/seat_service.py
  src/app/v1/user/entity/user.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schemas/user.py
  src/core/configs/seat_layouts.py
Labels: enhancement
